### ISSUE TITLE
500 - Internal Server Error when authorizing

### ISSUE THREAD

**Issue by tahosa** [ErinMorelli/em-slack-tableflip#6]
When trying to add the integration using the fast method, or on the first use after adding manually, I am prompted to authorize the app to post on my behalf. When I grant it, I am redirected to the heroku app where I get a `500 Internal Server Error` and the app does not get authorized.

**Comment by ErinMorelli** [comment]
Found this exception in the logs:

`TypeError: super() argument 1 must be type, not str`

Looks like something must have changed in one of the dependencies. Looking into it further.

**Comment by ErinMorelli** [comment]
@tahosa Can you re-try adding the app? I just pushed out a fix.

**Comment by tahosa** [comment]
This is now working, thanks! We can now flip tables to our hearts' content!
